spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: projectmanager
      password: password1
      database: projectmanager
      authentication-database: projectmanager
  application:
    name: Project Manager

server:
  context-path: /project-manager
